---
# Copyright 2019 Nokia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

dependencies:
  - role: cert
    instance: "cpuwebhook"
    cert_name: "cpuwebhook.crt"
    key_name: "cpuwebhook.key"
    cert_path: /etc/kubernetes/ssl
    alt_names:
      dns:
        - "cpu-dev-pod-mutator-svc.kube-system.svc.{{ caas.dns_domain }}"
        - "cpu-dev-pod-mutator-svc.kube-system.svc"
    become: true
    become_user: "root"

  - role: cert
    instance: "prometheus"
    cert_name: "prometheus.crt"
    key_name: "prometheus.key"
    common_name: "prometheus"
    cert_path: /etc/kubernetes/ssl
    alt_names:
      dns:
        - "{{ caas.prometheus_url }}"
    become: true
    become_user: "root"

  - role: cert
    instance: "metrics-server"
    cert_name: "metrics-server.crt"
    key_name: "metrics-server.key"
    common_name: "metrics-server"
    cert_path: /etc/metrics-server/ssl
    alt_names:
      dns:
        - "metrics-server.kube-system.svc.{{ caas.dns_domain }}"
        - metrics-server.kube-system.svc
    become: true
    become_user: "root"
