---
# Copyright 2019 Nokia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: retrieve filesystem
  shell: file -Ls {{device}} | grep "filesystem"
  register: filesystem_tmp
  failed_when: filesystem_tmp.rc != 0 and filesystem_tmp.rc != 1
  become: true
  become_user: "root"

- debug:
    msg: "Filesystem not found on device {{device}}!"
  when: filesystem_tmp.rc == 1

- name: set filesystem variable
  set_fact:
    filesystem: "{{ filesystem_tmp }}"

- name: retrieve filesystem_type
  shell: file -Ls "{{device}}" | awk -F" filesystem " '{print($1)}' | awk -F" " '{print($NF)}'
  register: filesystem_type_tmp
  when: filesystem_tmp.rc == 0
  become: true
  become_user: "root"

- name: set filesystem type variable
  set_fact:
    filesystem_type: "{{ filesystem_type_tmp }}"
  when: filesystem_tmp.rc == 0
