{{/*
Copyright 2019 Nokia

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}
{{ if .Values.elasticsearch.required }}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: elasticsearch-data
    component: "{{ .Values.elasticsearch.data.name }}"
  name: elasticsearch-data
  namespace: kube-system
spec:
  serviceName: elasticsearch-data
  replicas: {{ .Values.elasticsearch.data.replicas }}
  template:
    metadata:
      labels:
        app: elasticsearch-data
        component: "{{ .Values.elasticsearch.data.name }}"
    spec:
      priorityClassName: "system-cluster-critical"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: elasticsearch-data
                  component: "{{ .Values.elasticsearch.data.name }}"
      nodeSelector:
        nodetype: caas_master
      containers:
      - name: elasticsearch-data
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: CLUSTER_INITIAL_MASTER_NODES
          value: '{{ .Values.elasticsearch.clustermasternodes }}'
        - name: EXPECTED_MASTER_NODES
          value: '{{ .Values.elasticsearch.master.replicas }}'
        - name: EXPECTED_DATA_NODES
          value: '{{ .Values.elasticsearch.data.replicas }}'
        - name: RECOVER_AFTER_MASTER_NODES
          value: '{{ .Values.elasticsearch.master.replicas }}'
        - name: RECOVER_AFTER_DATA_NODES
          value: '{{ .Values.elasticsearch.data.replicas }}'
        - name: NODE_MASTER
          value: "false"
        - name: NODE_INGEST
          value: "true"
        - name: NODE_DATA
          value: "true"
        - name: DISCOVERY_SERVICE
          value: {{ .Values.elasticsearch.url }}
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: ES_JAVA_OPTS
          value: "-Xms{{ .Values.elasticsearch.java_heap_request }} -Xmx{{ .Values.elasticsearch.java_heap_max }} -Dmapper.allow_dots_in_name=true"
        {{- range $key, $value :=  .Values.elasticsearch.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        image: {{ .Values.elasticsearch.image_name }}
        command: ["/usr/bin/supervisord","-n","-c","/etc/supervisord.conf"]
        resources:
          limits:
            cpu: "{{ .Values.elasticsearch.cpu_limit }}"
            memory: "{{ .Values.elasticsearch.memory_limit }}"
          requests:
            cpu: "100m"
            memory: "{{ .Values.elasticsearch.memory_request }}"
        readinessProbe:
          tcpSocket:
            port: {{ .Values.elasticsearch.port }}
          initialDelaySeconds: 5
        livenessProbe:
          tcpSocket:
            port: {{ .Values.elasticsearch.port }}
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        volumeMounts:
        - name: time-mount
          mountPath: /etc/localtime
          readOnly: true
        - mountPath: /usr/share/elasticsearch/data
          name: data
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: elasticsearch-config
          subPath: elasticsearch.yml
        - mountPath: /etc/supervisord.conf
          name: supervisord-config
          subPath: supervisord.conf
        - mountPath: /etc/cron.hourly/elasticsearch-logrotate.sh
          name: elasticsearch-logrotate.sh
          subPath: elasticsearch-logrotate.sh
        - mountPath: /usr/share/elasticsearch/elasticsearch-setindex.sh
          name: elasticsearch-setindex.sh
          subPath: elasticsearch-setindex.sh
      terminationGracePeriodSeconds: {{ .Values.elasticsearch.data.terminationGracePeriodSeconds }}
      volumes:
        - name: time-mount
          hostPath:
            path: /etc/localtime
        - name: elasticsearch-config
          configMap:
            name: elasticsearch
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
                mode: 0644
        - name: supervisord-config
          configMap:
            name: elasticsearch
            items:
              - key: supervisord.conf
                path: supervisord.conf
                mode: 0644
        - name: elasticsearch-logrotate.sh
          configMap:
            name: elasticsearch
            items:
              - key: elasticsearch-logrotate.sh
                path: elasticsearch-logrotate.sh
                mode: 0755
        - name: elasticsearch-setindex.sh
          configMap:
            name: elasticsearch
            items:
              - key: elasticsearch-setindex.sh
                path: elasticsearch-setindex.sh
                mode: 0755
        - name: data
          hostPath:
            path: /var/log/elasticsearch
{{ end }}
