{{/*
Copyright 2019 Nokia

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}
{{ if .Values.elasticsearch.required }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch-data
    component: "{{ .Values.elasticsearch.data.name }}"
  name: elasticsearch-data
  namespace: kube-system
spec:
  ports:
    - port: {{ .Values.elasticsearch.port }}
      name: http
      protocol: TCP
    - port: {{ .Values.elasticsearch.port_for_cluster_communication }}
      name: node-to-node
      protocol: TCP
  selector:
    app: elasticsearch-data
    component: "{{ .Values.elasticsearch.data.name }}"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch-master
    component: "{{ .Values.elasticsearch.master.name }}"
  name: elasticsearch-logging
  namespace: kube-system
spec:
  ports:
    - port: {{ .Values.elasticsearch.port }}
      name: http
      protocol: TCP
    - port: {{ .Values.elasticsearch.port_for_cluster_communication }}
      name: node-to-node
      protocol: TCP
  selector:
    app: elasticsearch-master
    component: "{{ .Values.elasticsearch.master.name }}"
{{ end }}
