{{/*
Copyright 2019 Nokia

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    {{ .Values.kubernetes_component_label }}: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      {{ .Values.kubernetes_component_label }}: fluentd-logging
  template:
    metadata:
      annotations:
        config/timestamp: "{{ .Values.fluentd.config_timestamp }}"
        danm.k8s.io/interfaces: |
          [
            {
              "network":"flannel"
            }
          ]
      labels:
        {{ .Values.kubernetes_component_label }}: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: fluentd
        image: {{ .Values.fluentd.image_name }}
        command:
        - "/bin/entrypoint.sh"
        - "fluentd"
        - "-c"
        - "/fluentd/etc/fluent.conf"
        - "-p"
        - "/fluentd/plugins"
        securityContext:
          capabilities:
            add:
              - ALL
        env:
          - name:  KUBERNETES_SERVICE_HOST
            value: {{ .Values.fluentd.apiserver_service_name }}
          - name:  KUBERNETES_SERVICE_PORT
            value: "{{ .Values.fluentd.apiserver_svc_port }}"
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: {{ .Values.elasticsearch.host }}
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "{{ .Values.elasticsearch.port }}"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: {{ .Values.elasticsearch.scheme }}
          - name: FLUENT_ELASTICSEARCH_USER
            value: {{ .Values.elasticsearch.user | default "elastic" }}
          - name: FLUENT_ELASTICSEARCH_PASSWORD
            value: {{ .Values.elasticsearch.passwd  | default "changeme" }}
          - name: FLUENT_ELASTICSEARCH_SSL
            value: "false"
          - name: FLUENTD_OPT
            value: ""
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 1
        volumeMounts:
        - name: time-mount
          mountPath: /etc/localtime
          readOnly: true
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
        - name: fluentd-secrets
          mountPath: /etc/fluentd/ssl
          readOnly: true
        - name: fluentd-config
          mountPath: /fluentd/etc
          readOnly: true
        - name: varlibfluentd
          mountPath: /var/lib/fluentd
      terminationGracePeriodSeconds: 30
      volumes:
      - name: time-mount
        hostPath:
          path: /etc/localtime
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentd-secrets
        hostPath:
          path: /etc/fluentd/ssl
      - name: fluentd-config
        configMap:
          name: fluentd-cm
      - name: varlibfluentd
        hostPath:
          path: /var/lib/fluentd
      serviceAccountName: fluentd
