kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-pvc
  namespace: kube-system
  annotations:
      nokia.k8s.io/nodeSelector: '{"nodetype":"caas-master"}'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.prometheus.storage_size }}
