{{ if .Values.storagelocalstaticprovisioner.required }}
---
# Source: provisioner/templates/provisioner.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: local-provisioner-config
  namespace: kube-system
data:
  storageClassMap: |
    local-volume:
       hostDir: {{ .Values.storagelocalstaticprovisioner.local_storage_dir }}
       mountDir: {{ .Values.storagelocalstaticprovisioner.local_storage_dir }}
       blockCleanerCommand:
         - "/scripts/shred.sh"
         - "2"
       volumeMode: Filesystem
       fsType: xfs
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: local-volume-provisioner
  namespace: kube-system
  labels:
    app: local-volume-provisioner
spec:
  selector:
    matchLabels:
      app: local-volume-provisioner
  template:
    metadata:
      labels:
        app: local-volume-provisioner
      annotations:
        danm.k8s.io/interfaces: |
          [
            {
              "tenantNetwork": "default", "ip":"dynamic"
            }
          ]
    spec:
      serviceAccountName: local-storage-admin
      containers:
        - image: {{ .Values.storagelocalstaticprovisioner.image_name }}
          imagePullPolicy: "Always"
          name: provisioner
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /etc/provisioner/config
              name: provisioner-config
              readOnly: true
            - mountPath:  {{ .Values.storagelocalstaticprovisioner.local_storage_dir }}
              name: local-volume
              mountPropagation: "HostToContainer"
      volumes:
        - name: provisioner-config
          configMap:
            name: local-provisioner-config
        - name: local-volume
          hostPath:
            path: {{ .Values.storagelocalstaticprovisioner.local_storage_dir }}
{{ end }}

