{{/*
Copyright 2019 Nokia

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}
{{ if .Values.cpupooler.required }}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: cpu-device-pod-mutator-webhook-config
  namespace: kube-system
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-failed, before-hook-creation
webhooks:
  - name: cpu-dev-mutator.nokia.k8s.io
    clientConfig:
      service:
        name: cpu-dev-pod-mutator-svc
        namespace: kube-system
        path: "/mutating-pods"
      caBundle: "{{ .Values.cpupooler.webhook_ca_bundle }}"
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
{{ end }}
